on:
  workflow_dispatch:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
          # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables
          # Trigger more steps using "if: ${{ steps.release.outputs.release_created }}"
